name: Bugs
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: Lversion
    attributes:
      label: Plugin's version
    validations:
      required: true
  - type: input
    id: Pversion
    attributes:
      label: Playnite's version
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log
      description: Please include any relevant log. This will be automatically formatted into code, so no need for backticks.
      render: shell
